"""add notification_channels

Revision ID: 433bbf784555
Revises: 9a8b47f70757
Create Date: 2026-04-28 19:23:06.743282
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "433bbf784555"
down_revision: Union[str, None] = "9a8b47f70757"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply forward migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_channels",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Enum("telegram", name="channel_type"), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "client_id",
            "type",
            "address",
            name="uq_notification_channels_client_type_address",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Apply reverse migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification_channels")
    # ### end Alembic commands ###
