"""add leads

Revision ID: 4d966a48a65f
Revises: d43772e0bfa8
Create Date: 2026-04-28 19:23:44.636915
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d966a48a65f"
down_revision: Union[str, None] = "d43772e0bfa8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply forward migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leads",
        sa.Column("landing_id", sa.UUID(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "source_meta",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["landing_id"], ["landings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_leads_landing_id_created_at",
        "leads",
        ["landing_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Apply reverse migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_leads_landing_id_created_at", table_name="leads")
    op.drop_table("leads")
    # ### end Alembic commands ###
