"""add landings

Revision ID: 8ed0d307bb9c
Revises: 1913d3382af2
Create Date: 2026-04-28 19:22:32.693663
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ed0d307bb9c"
down_revision: Union[str, None] = "1913d3382af2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply forward migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "landings",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("api_token_hash", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_token_hash"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(
        op.f("ix_landings_client_id"), "landings", ["client_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Apply reverse migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_landings_client_id"), table_name="landings")
    op.drop_table("landings")
    # ### end Alembic commands ###
