"""add linking_codes

Revision ID: 9a8b47f70757
Revises: 8ed0d307bb9c
Create Date: 2026-04-28 19:22:47.817381
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a8b47f70757"
down_revision: Union[str, None] = "8ed0d307bb9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply forward migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "linking_codes",
        sa.Column("landing_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_by_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["landing_id"], ["landings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        "ix_linking_codes_active_expires_at",
        "linking_codes",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("used_at IS NULL"),
    )
    op.create_index(
        op.f("ix_linking_codes_landing_id"),
        "linking_codes",
        ["landing_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Apply reverse migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_linking_codes_landing_id"), table_name="linking_codes")
    op.drop_index(
        "ix_linking_codes_active_expires_at",
        table_name="linking_codes",
        postgresql_where=sa.text("used_at IS NULL"),
    )
    op.drop_table("linking_codes")
    # ### end Alembic commands ###
