"""add deliveries

Revision ID: ba119a9427e2
Revises: 4d966a48a65f
Create Date: 2026-04-28 19:24:00.397759
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba119a9427e2"
down_revision: Union[str, None] = "4d966a48a65f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply forward migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deliveries",
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "sent", "failed", name="delivery_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["notification_channels.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lead_id", "channel_id", name="uq_deliveries_lead_channel"),
    )
    op.create_index(
        op.f("ix_deliveries_channel_id"), "deliveries", ["channel_id"], unique=False
    )
    op.create_index(
        "ix_deliveries_pending_created_at",
        "deliveries",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Apply reverse migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_deliveries_pending_created_at",
        table_name="deliveries",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(op.f("ix_deliveries_channel_id"), table_name="deliveries")
    op.drop_table("deliveries")
    # ### end Alembic commands ###
