"""add landing_routes

Revision ID: d43772e0bfa8
Revises: 433bbf784555
Create Date: 2026-04-28 19:23:23.585378
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d43772e0bfa8"
down_revision: Union[str, None] = "433bbf784555"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply forward migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "landing_routes",
        sa.Column("landing_id", sa.UUID(), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["notification_channels.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["landing_id"], ["landings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "landing_id", "channel_id", name="uq_landing_routes_landing_channel"
        ),
    )
    op.create_index(
        op.f("ix_landing_routes_channel_id"),
        "landing_routes",
        ["channel_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Apply reverse migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_landing_routes_channel_id"), table_name="landing_routes")
    op.drop_table("landing_routes")
    # ### end Alembic commands ###
